<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
      <TargetFramework>net8.0</TargetFramework>
      <Nullable>enable</Nullable>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="**\*.sql" />
    <None Remove="**\*.tql" />
    <EmbeddedResource Include="**\*.sql" />
    <EmbeddedResource Include="**\*.tql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CK.DB.User.UserPassword" Version="28.0.3--ci.5" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\CK.DB.User.UserBanned\CK.DB.User.UserBanned.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Update="DotNet.ReproducibleBuilds" Version="2.0.5" />
    <PackageReference Update="Microsoft.VisualStudio.Threading.Analyzers" Version="18.7.23">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers</IncludeAssets>
    </PackageReference>
  </ItemGroup>

</Project>
